name: Random Push to GitHub

on:
  schedule:
    - cron: '0 */6 * * *'  # This runs every 6 hours (adjust as needed)
  workflow_dispatch:  # Allows you to manually trigger this action if needed

jobs:
  random-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # This checks out the code

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'  # You can change the Python version if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install random  # Install the necessary dependencies

      - name: Run Random Push Script
        run: |
          python push_random_code.py 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token stored as a secret
